name: deepml-env
channels:
 - defaults
 - conda-forge
 - ioam
 - soumith
dependencies:
 - autopep8
 - distributed
 - flake8
 - isort
 - jupyterlab
 - jupyter
 - mypy
 - nomkl
 - pandas
 - pytest
 - python
 - scikit-learn
 - scipy
 - tqdm
 - unidecode
 - gensim
 - sphinx
 - pytorch
 - torchvision
 - tqdm
 - seaborn
 - matplotlib
 - pip:
    - pretrainedmodels
    - pillow